spring:
  application:
    name: test-application
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080